name: "💡 New Content Suggestion"
description: >-
  Suggest new feature or a change to an existing feature. Completing this forms indicates agreement to the CLA[https://github.com/fido-alliance/credential-exchange-feedback/blob/main/FIDO_CLA.md]
labels:
  - New-Feature
  - needs-triage
body:
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the proposed feature. Why is it needed? What gap
        will it fill? Who is the intended audience? What scenarios will it address?
      placeholder: |
        Try formulating the need for this feature as a user story.

  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add additional context.
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: Proposed Feature Type
      description: >-
        Choose the type or types of documentation required.
      multiple: true
      options:
        - Best Practice
        - User Journey
        - Protocol Deep Dive
        - FAQ Item
        - Demo
        - Other / Unknown
  - type: input
    id: title
    validations:
      required: false
    attributes:
      label: Proposed Feature Name
  - type: textarea
    id: related_documents
    validations:
      required: false
    attributes:
      label: Related Articles
      description: >-
        Provide a list of links to the documentation page(s) that are related to this request. Use
        the markdown list syntax for each item. If the entire article is relevant, just link to the
        permalink for its source or the live page. If only a section of the article is relevant, use
        the permalink to the lines for the most relevant section of the source or the anchor link to
        the nearest header for the relevant content instead of the page itself.
      placeholder: |
        - https://fidoalliance.org/specs/cx/cxf-v1.0-wd-20240522.html
        - https://fidoalliance.org/specs/cx/cxp-v1.0-wd-20240522.html
